{{- if or (eq .Values.environment.data.LOG_STORE "local") (eq .Values.environment.data.VECTOR_STORE "local") }}
{{- if .Values.minio.authKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.secretName" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.minio.authKey.accessKey | default "portkey" | b64enc }}
  secretKey: {{ .Values.minio.authKey.secretKey | default "portkey123" | b64enc }}
{{- end }}
{{- end }}
