{{- if and .Values.minio.enabled .Values.minio.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.secretName" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.minio.secret.accessKey | b64enc }}
  secretKey: {{ .Values.minio.secret.secretKey | b64enc }}
{{- end }}