{{- if .Values.minio.enabled }}
{{- if .Values.minio.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio.serviceAccountName" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    {{- with .Values.minio.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.minio.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

