{{- if and .Values.milvus.enabled .Values.minio.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
data:
  user.yaml: |
    common:
      security:
        authorizationEnabled: true
{{- end }}