{{- if eq .Values.environment.data.VECTOR_STORE "local" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
data:
  user.yaml: |
    common:
      security:
        authorizationEnabled: true
{{- end }}