{{- if eq .Values.environment.data.VECTOR_STORE "local" }}
apiVersion: v1
kind: Service
metadata:
  name: milvus
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
    {{- with .Values.milvus.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.milvus.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.milvus.service.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.milvus.grpcPort | default 19530 }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.milvus.httpPort | default 9091 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "milvus.selectorLabels" . | nindent 4 }}
{{- end }}