apiVersion: v2
name: app
description: Helm chart to deploy the Portkey Full Stack application and all dependent services.
home: https://portkey.ai/
icon: https://avatars.githubusercontent.com/u/131141116?s=200&v=4
type: application
appVersion: "1.7.0"
version: 1.4.2
maintainers:
  - name: Ayush
    email: ayush@portkey.ai
    url: https://github.com/ayush-portkey
  - name: Sai Krishna
    email: sai.t@portkey.ai
    url: https://github.com/sk-portkey
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/Portkey-AI/helm